# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90e7f541e17791a73248a819b14c721e4a19191dd9eab0b1ef60be2a6b48efb09c28fa04f2a9a3bf8ce298217b900b047531966096f48ce560baf6ebe2251d21

test:
  secret_key_base: 272da6c2f6d57119102cc827e98ce4642a2c852fe81914afc10fe0f9bdfb0bbeb27d672fdc4fd7d0bc52ecd68347067f8e2895e395d8ced0e86bce9eb6679fc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
